### ISSUE TITLE
Add OpenTelemetry

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/ts-client#26]
**Is your feature request related to a problem? Please describe.**

With a good portion of the PlaceOS backend instrumented, having a continuum of telemetry from the frontend to the backend would seal up the remaining gaps in our application observability 

**Describe the solution you'd like**

Add OpenTelemetry

**Comment by MrYuion** [comment]
@caspiano, do we have a place to export the data from the frontend?

**Comment by caspiano** [comment]
This is intended to be configured per instance. We do have a dev instance that you can test this against.

**Comment by MrYuion** [comment]
That's fine. It does help to have a concrete place to export to for testing though.
